volumes:
  db_data: {}
services:
  app:
    build: .
    # container_name: nestjs-app
    command: npm run start:debug
    environment:
      NPM_INSTALL: ENABLE
      TYPEORM_MIGRATION: ENABLE
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES=testapi,testapitesting
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - db_data:/data/postgres
    ports:
      - 5432:5432
